Debug YAML

diff --git a/.github/workflows/api-test.yaml b/.github/workflows/api-test.yaml
--- a/.github/workflows/api-test.yaml
+++ b/.github/workflows/api-test.yaml
@@ -25,7 +25,12 @@ jobs:
           AUTH_USER: ${{ secrets.POSTMAN_USERNAME }}
           AUTH_PASS: ${{ secrets.POSTMAN_PASSWORD }}
         run: |
+          if [ -z "$AUTH_USER" ] || [ -z "$AUTH_PASS" ]; then
+            echo "Error: Secrets are not being retrieved correctly."
+            exit 1
+          fi
+
           newman run Restful-Booker.postman_collection.json \
           -e Restful-Booker.postman_environment.json \
-          --env-var "username=${{ env.AUTH_USER }}" \
-          --env-var "password=${{ env.AUTH_PASS }}"
+          --env-var "username=$AUTH_USER" \
+          --env-var "password=$AUTH_PASS"
